### ISSUE TITLE
Atom 1.25.0 で linter-textlint 4.0.0 のインストールに失敗する

### ISSUE THREAD

**Issue by nyoro712** [1000ch/linter-textlint#43]
Atom 1.25.0 に linter-textlint 4.0.0 をインストールしようとしたところ、以下のようなエラーメッセージが出てインストールできませんでした。

```
> utf-8-validate@4.0.0 install C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529\node_modules\linter-textlint\node_modules\utf-8-validate
> prebuild-install || node-gyp rebuild


C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529\node_modules\linter-textlint\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "D:\Atom\Atom\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Atom\Atom\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529
`-- (empty)


prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds\utf-8-validate-v4.0.0-electron-v54-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\[MyName]\.atom\.apm\_prebuilds\https-github.com-websockets-utf-8-validate-releases-download-v4.0.0-utf-8-validate-v4.0.0-electron-v54-win32-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/utf-8-validate/releases/download/v4.0.0/utf-8-validate-v4.0.0-electron-v54-win32-x64.tar.gz
prebuild-install http 404 https://github.com/websockets/utf-8-validate/releases/download/v4.0.0/utf-8-validate-v4.0.0-electron-v54-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=1.7.11 runtime=electron arch=x64 platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\Atom\Atom\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at D:\Atom\Atom\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at D:\Atom\Atom\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Atom\\Atom\\resources\\app\\apm\\bin\\node.exe" "D:\\Atom\\Atom\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529\node_modules\linter-textlint\node_modules\utf-8-validate
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529\package.json'
npm WARN apm-install-dir-118223-10812-ap0x0t.87s55hr529 No description
npm WARN apm-install-dir-118223-10812-ap0x0t.87s55hr529 No repository field.
npm WARN apm-install-dir-118223-10812-ap0x0t.87s55hr529 No README data
npm WARN apm-install-dir-118223-10812-ap0x0t.87s55hr529 No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "D:\\Atom\\Atom\\resources\\app\\apm\\bin\\node.exe" "D:\\Atom\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\[MyName]\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\[MyName]\\.atom\\.apmrc" "install" "C:\\Users\\[MyName]\\AppData\\Local\\Temp\\d-118223-10812-11th3u6.6bu51att9\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! utf-8-validate@4.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@4.0.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs utf-8-validate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529\npm-debug.log
npm ERR! code 1
```

（ファイルパス中のユーザ名は `[MyName]` に置き換えています）

エラーメッセージの最後3行で `C:\Users\[MyName]\AppData\Local\Temp\apm-install-dir-118223-10812-ap0x0t.87s55hr529\npm-debug.log` なるファイルを含めるように書かれていますが、該当するファイルが無かったので添付しません。

Atom 1.25.0 は64bitのWindows用で、 https://github.com/atom/atom/releases にある「atom-x64-windows.zip」をダウンロード・解凍して導入しました。

OSはWindows 10 Proの64bit版のバージョン1709です。

**Comment by azu** [comment]
textlintが使ってる https://www.npmjs.com/package/utf-8-validate がダメそうな感じがしますね。
ネイティブモジュールだからAtomと相性がよくない感じがしていますね。

https://github.com/textlint/textlint/blob/25d10a94e496a23eca549e4395e998d711e34bfe/packages/textlint/src/config/config-loader.ts#L6

textlint側でutf-8-validateを使わないようにするのが良さそうな気がします。

**Comment by azu** [comment]
@nyoro712 ネイティブモジュール([utf-8-validate](https://www.npmjs.com/package/utf-8-validate))を使わない[textlint@10.1.5](https://github.com/textlint/textlint/releases/tag/textlint%4010.1.5 "textlint@10.1.5")をリリースしました。
もう一度、linter-textlintをインストールし直すと恐らく最新版をtextlintをインストールすると思うので、これでインストールできるか確認お願いできますか?

**Comment by nyoro712** [comment]
@azu インストールできました。lintも問題無く行われます。ありがとうございました。

**Comment by azu** [comment]
@nyoro712 ご確認ありがとうございます！

**Comment by 1000ch** [comment]
@nyoro712 @azu 
ありがとうございます、`package-lock.json` をアップデートしたものを `v4.1.0` としてリリースしました。
